base_url = "/"
title = "Oat UI"
compile_sass = false
build_search_index = false

[markdown.highlighting]
theme = "material-theme"

[extra]
description = "Oat - Ultra-lightweight, semantic, zero-dependency HTML UI component library"
